// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AesReqData struct {
	ClientVersion        int32    `protobuf:"varint,1,opt,name=clientVersion,proto3" json:"clientVersion,omitempty"`
	Uin                  int64    `protobuf:"varint,2,opt,name=uin,proto3" json:"uin,omitempty"`
	AutoAuthKey          []byte   `protobuf:"bytes,3,opt,name=autoAuthKey,proto3" json:"autoAuthKey,omitempty"`
	DeviceId             string   `protobuf:"bytes,4,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	DeviceType           string   `protobuf:"bytes,5,opt,name=deviceType,proto3" json:"deviceType,omitempty"`
	DeviceName           string   `protobuf:"bytes,6,opt,name=deviceName,proto3" json:"deviceName,omitempty"`
	Imei                 string   `protobuf:"bytes,7,opt,name=imei,proto3" json:"imei,omitempty"`
	TimeZone             string   `protobuf:"bytes,8,opt,name=timeZone,proto3" json:"timeZone,omitempty"`
	Language             string   `protobuf:"bytes,9,opt,name=language,proto3" json:"language,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AesReqData) Reset()         { *m = AesReqData{} }
func (m *AesReqData) String() string { return proto.CompactTextString(m) }
func (*AesReqData) ProtoMessage()    {}
func (*AesReqData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *AesReqData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AesReqData.Unmarshal(m, b)
}
func (m *AesReqData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AesReqData.Marshal(b, m, deterministic)
}
func (m *AesReqData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AesReqData.Merge(m, src)
}
func (m *AesReqData) XXX_Size() int {
	return xxx_messageInfo_AesReqData.Size(m)
}
func (m *AesReqData) XXX_DiscardUnknown() {
	xxx_messageInfo_AesReqData.DiscardUnknown(m)
}

var xxx_messageInfo_AesReqData proto.InternalMessageInfo

func (m *AesReqData) GetClientVersion() int32 {
	if m != nil {
		return m.ClientVersion
	}
	return 0
}

func (m *AesReqData) GetUin() int64 {
	if m != nil {
		return m.Uin
	}
	return 0
}

func (m *AesReqData) GetAutoAuthKey() []byte {
	if m != nil {
		return m.AutoAuthKey
	}
	return nil
}

func (m *AesReqData) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *AesReqData) GetDeviceType() string {
	if m != nil {
		return m.DeviceType
	}
	return ""
}

func (m *AesReqData) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *AesReqData) GetImei() string {
	if m != nil {
		return m.Imei
	}
	return ""
}

func (m *AesReqData) GetTimeZone() string {
	if m != nil {
		return m.TimeZone
	}
	return ""
}

func (m *AesReqData) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

type RsaReqData struct {
	CliRandomEncryKey    string   `protobuf:"bytes,1,opt,name=cliRandomEncryKey,proto3" json:"cliRandomEncryKey,omitempty"`
	UserToken            string   `protobuf:"bytes,2,opt,name=userToken,proto3" json:"userToken,omitempty"`
	CliPubEcdhkey        []byte   `protobuf:"bytes,3,opt,name=cliPubEcdhkey,proto3" json:"cliPubEcdhkey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RsaReqData) Reset()         { *m = RsaReqData{} }
func (m *RsaReqData) String() string { return proto.CompactTextString(m) }
func (*RsaReqData) ProtoMessage()    {}
func (*RsaReqData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *RsaReqData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RsaReqData.Unmarshal(m, b)
}
func (m *RsaReqData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RsaReqData.Marshal(b, m, deterministic)
}
func (m *RsaReqData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RsaReqData.Merge(m, src)
}
func (m *RsaReqData) XXX_Size() int {
	return xxx_messageInfo_RsaReqData.Size(m)
}
func (m *RsaReqData) XXX_DiscardUnknown() {
	xxx_messageInfo_RsaReqData.DiscardUnknown(m)
}

var xxx_messageInfo_RsaReqData proto.InternalMessageInfo

func (m *RsaReqData) GetCliRandomEncryKey() string {
	if m != nil {
		return m.CliRandomEncryKey
	}
	return ""
}

func (m *RsaReqData) GetUserToken() string {
	if m != nil {
		return m.UserToken
	}
	return ""
}

func (m *RsaReqData) GetCliPubEcdhkey() []byte {
	if m != nil {
		return m.CliPubEcdhkey
	}
	return nil
}

type ClientInfo struct {
	AesData              []byte   `protobuf:"bytes,1,opt,name=aesData,proto3" json:"aesData,omitempty"`
	RsaData              []byte   `protobuf:"bytes,2,opt,name=rsaData,proto3" json:"rsaData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientInfo) Reset()         { *m = ClientInfo{} }
func (m *ClientInfo) String() string { return proto.CompactTextString(m) }
func (*ClientInfo) ProtoMessage()    {}
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *ClientInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientInfo.Unmarshal(m, b)
}
func (m *ClientInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientInfo.Marshal(b, m, deterministic)
}
func (m *ClientInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientInfo.Merge(m, src)
}
func (m *ClientInfo) XXX_Size() int {
	return xxx_messageInfo_ClientInfo.Size(m)
}
func (m *ClientInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClientInfo proto.InternalMessageInfo

func (m *ClientInfo) GetAesData() []byte {
	if m != nil {
		return m.AesData
	}
	return nil
}

func (m *ClientInfo) GetRsaData() []byte {
	if m != nil {
		return m.RsaData
	}
	return nil
}

//response
type AuthRet struct {
	ErrMsg               string   `protobuf:"bytes,1,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	Ret                  int32    `protobuf:"varint,2,opt,name=ret,proto3" json:"ret,omitempty"`
	AuthSectResp         []byte   `protobuf:"bytes,3,opt,name=authSectResp,proto3" json:"authSectResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRet) Reset()         { *m = AuthRet{} }
func (m *AuthRet) String() string { return proto.CompactTextString(m) }
func (*AuthRet) ProtoMessage()    {}
func (*AuthRet) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *AuthRet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRet.Unmarshal(m, b)
}
func (m *AuthRet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRet.Marshal(b, m, deterministic)
}
func (m *AuthRet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRet.Merge(m, src)
}
func (m *AuthRet) XXX_Size() int {
	return xxx_messageInfo_AuthRet.Size(m)
}
func (m *AuthRet) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRet.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRet proto.InternalMessageInfo

func (m *AuthRet) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *AuthRet) GetRet() int32 {
	if m != nil {
		return m.Ret
	}
	return 0
}

func (m *AuthRet) GetAuthSectResp() []byte {
	if m != nil {
		return m.AuthSectResp
	}
	return nil
}

type AuthSectResp struct {
	ServerTime int32 `protobuf:"varint,1,opt,name=serverTime,proto3" json:"serverTime,omitempty"`
	//客户端得到svrPubEcdhkey后是可以通过ecdh算法算出这个key的, server ecdhAesKey == client ecdhAesKey
	//encSessionKey=AES_Enc(ecdhAesKey, SessionKey)
	//auth通过后，之后的业务数据都使用SessionKey进行AES
	EncSessionKey        []byte   `protobuf:"bytes,4,opt,name=encSessionKey,proto3" json:"encSessionKey,omitempty"`
	SvrPubEcdhkey        []byte   `protobuf:"bytes,5,opt,name=svrPubEcdhkey,proto3" json:"svrPubEcdhkey,omitempty"`
	AutoAuthKey          []byte   `protobuf:"bytes,3,opt,name=autoAuthKey,proto3" json:"autoAuthKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthSectResp) Reset()         { *m = AuthSectResp{} }
func (m *AuthSectResp) String() string { return proto.CompactTextString(m) }
func (*AuthSectResp) ProtoMessage()    {}
func (*AuthSectResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{4}
}

func (m *AuthSectResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthSectResp.Unmarshal(m, b)
}
func (m *AuthSectResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthSectResp.Marshal(b, m, deterministic)
}
func (m *AuthSectResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthSectResp.Merge(m, src)
}
func (m *AuthSectResp) XXX_Size() int {
	return xxx_messageInfo_AuthSectResp.Size(m)
}
func (m *AuthSectResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthSectResp.DiscardUnknown(m)
}

var xxx_messageInfo_AuthSectResp proto.InternalMessageInfo

func (m *AuthSectResp) GetServerTime() int32 {
	if m != nil {
		return m.ServerTime
	}
	return 0
}

func (m *AuthSectResp) GetEncSessionKey() []byte {
	if m != nil {
		return m.EncSessionKey
	}
	return nil
}

func (m *AuthSectResp) GetSvrPubEcdhkey() []byte {
	if m != nil {
		return m.SvrPubEcdhkey
	}
	return nil
}

func (m *AuthSectResp) GetAutoAuthKey() []byte {
	if m != nil {
		return m.AutoAuthKey
	}
	return nil
}

func init() {
	proto.RegisterType((*AesReqData)(nil), "bubble.auth.AesReqData")
	proto.RegisterType((*RsaReqData)(nil), "bubble.auth.RsaReqData")
	proto.RegisterType((*ClientInfo)(nil), "bubble.auth.ClientInfo")
	proto.RegisterType((*AuthRet)(nil), "bubble.auth.AuthRet")
	proto.RegisterType((*AuthSectResp)(nil), "bubble.auth.AuthSectResp")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 441 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xcf, 0x8a, 0x13, 0x41,
	0x10, 0xc6, 0x99, 0x64, 0x92, 0x6c, 0x2a, 0x11, 0xb4, 0x11, 0x6d, 0x16, 0x91, 0x61, 0xf0, 0x90,
	0x83, 0xe4, 0xa0, 0x57, 0x0f, 0x46, 0x77, 0x0f, 0x8b, 0x28, 0xd2, 0x1b, 0x14, 0xf6, 0xd6, 0x33,
	0x29, 0x93, 0x66, 0x33, 0x3d, 0xd9, 0xfe, 0x13, 0xc8, 0xc5, 0x47, 0xf0, 0x09, 0x7c, 0x58, 0xa9,
	0xee, 0x49, 0x32, 0x83, 0x87, 0xbd, 0xd5, 0xf7, 0xfb, 0xa6, 0xe9, 0xaa, 0xaf, 0x6b, 0x00, 0xa4,
	0x77, 0x9b, 0xf9, 0xce, 0xd4, 0xae, 0x66, 0x93, 0xc2, 0x17, 0xc5, 0x16, 0xe7, 0x84, 0xf2, 0x3f,
	0x3d, 0x80, 0x05, 0x5a, 0x81, 0x0f, 0x57, 0xd2, 0x49, 0xf6, 0x06, 0x9e, 0x94, 0x5b, 0x85, 0xda,
	0xfd, 0x40, 0x63, 0x55, 0xad, 0x79, 0x92, 0x25, 0xb3, 0x81, 0xe8, 0x42, 0xf6, 0x14, 0xfa, 0x5e,
	0x69, 0xde, 0xcb, 0x92, 0x59, 0x5f, 0x50, 0xc9, 0x32, 0x98, 0x48, 0xef, 0xea, 0x85, 0x77, 0x9b,
	0x2f, 0x78, 0xe0, 0xfd, 0x2c, 0x99, 0x4d, 0x45, 0x1b, 0xb1, 0x4b, 0xb8, 0x58, 0xe1, 0x5e, 0x95,
	0x78, 0xb3, 0xe2, 0x69, 0x96, 0xcc, 0xc6, 0xe2, 0xa4, 0xd9, 0x6b, 0x80, 0x58, 0x2f, 0x0f, 0x3b,
	0xe4, 0x83, 0xe0, 0xb6, 0xc8, 0xd9, 0xff, 0x26, 0x2b, 0xe4, 0xc3, 0xb6, 0x4f, 0x84, 0x31, 0x48,
	0x55, 0x85, 0x8a, 0x8f, 0x82, 0x13, 0x6a, 0xba, 0xcf, 0xa9, 0x0a, 0xef, 0x6a, 0x8d, 0xfc, 0x22,
	0xde, 0x77, 0xd4, 0xe4, 0x6d, 0xa5, 0x5e, 0x7b, 0xb9, 0x46, 0x3e, 0x8e, 0xde, 0x51, 0xe7, 0xbf,
	0x01, 0x84, 0x95, 0xc7, 0x3c, 0xde, 0xc2, 0xb3, 0x72, 0xab, 0x84, 0xd4, 0xab, 0xba, 0xba, 0xd6,
	0xa5, 0x39, 0xd0, 0x74, 0x49, 0x38, 0xf2, 0xbf, 0xc1, 0x5e, 0xc1, 0xd8, 0x5b, 0x34, 0xcb, 0xfa,
	0x1e, 0x63, 0x3a, 0x63, 0x71, 0x06, 0x4d, 0xb6, 0xdf, 0x7d, 0x71, 0x5d, 0xae, 0x36, 0xf7, 0xa7,
	0x94, 0xba, 0x30, 0xff, 0x08, 0xf0, 0x39, 0x84, 0x7d, 0xa3, 0x7f, 0xd5, 0x8c, 0xc3, 0x48, 0xa2,
	0xa5, 0x56, 0xc2, 0xad, 0x53, 0x71, 0x94, 0xe4, 0x18, 0x2b, 0x83, 0xd3, 0x8b, 0x4e, 0x23, 0xf3,
	0x9f, 0x30, 0xa2, 0xd0, 0x05, 0x3a, 0xf6, 0x02, 0x86, 0x68, 0xcc, 0x57, 0xbb, 0x6e, 0x7a, 0x6e,
	0x14, 0x3d, 0xa0, 0x41, 0x17, 0x0e, 0x0e, 0x04, 0x95, 0x2c, 0x87, 0x29, 0xed, 0xc3, 0x2d, 0x96,
	0x4e, 0xa0, 0xdd, 0x35, 0xbd, 0x75, 0x58, 0xfe, 0x37, 0x81, 0xe9, 0xa2, 0x05, 0xe8, 0x5d, 0x2c,
	0x9a, 0x3d, 0x9a, 0xa5, 0xaa, 0xb0, 0x59, 0x95, 0x16, 0xa1, 0x89, 0x51, 0x97, 0xb7, 0x68, 0x69,
	0x6b, 0x28, 0xb9, 0x34, 0x4e, 0xdc, 0x81, 0xf4, 0x95, 0xdd, 0x9b, 0x56, 0x2e, 0x83, 0xf8, 0x55,
	0x07, 0x3e, 0xbe, 0x61, 0xef, 0xae, 0x20, 0xa5, 0x76, 0xd9, 0x07, 0x98, 0xc4, 0xf9, 0x1f, 0x3c,
	0x5a, 0xc7, 0x5e, 0xce, 0x5b, 0xfb, 0x3e, 0x3f, 0x67, 0x7b, 0xf9, 0xbc, 0x63, 0x34, 0x91, 0x7d,
	0x1a, 0xde, 0xa5, 0x6b, 0xb3, 0x2b, 0x8b, 0x61, 0xf8, 0x59, 0xde, 0xff, 0x0b, 0x00, 0x00, 0xff,
	0xff, 0x3f, 0x84, 0x92, 0x46, 0x3a, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthClient interface {
	AuthRequest(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (*AuthRet, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) AuthRequest(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (*AuthRet, error) {
	out := new(AuthRet)
	err := c.cc.Invoke(ctx, "/bubble.auth.auth/AuthRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
type AuthServer interface {
	AuthRequest(context.Context, *ClientInfo) (*AuthRet, error)
}

// UnimplementedAuthServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServer struct {
}

func (*UnimplementedAuthServer) AuthRequest(ctx context.Context, req *ClientInfo) (*AuthRet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthRequest not implemented")
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_AuthRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).AuthRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bubble.auth.auth/AuthRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).AuthRequest(ctx, req.(*ClientInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bubble.auth.auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthRequest",
			Handler:    _Auth_AuthRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
